# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# modelbuilder.py
# Created on: 2017-02-20 13:37:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.overwriteOutput = True

# Local variables:
filehdf= "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\source\\single\\MOD14A1.A2000049.h00v08.006.2015041132347.hdf"

rasterstif = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\single\\ModelBuilder.tif"

bandnum=str(1)
band1 = rasterstif +"\\Band_"+bandnum

ModBldBand_1 = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\single\\Band"+bandnum+".tif"

# Process: Extract Subdataset
arcpy.ExtractSubDataset_management(filehdf, rasterstif, "0")

# Process: Copy Raster
arcpy.CopyRaster_management(band1, ModBldBand_1, "", "", "0", "NONE", "NONE", "8_BIT_UNSIGNED", "NONE", "NONE")

