# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# raster2mosaic.py
# Created on: 2017-02-21 17:37:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
day = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\day"
D049_Y2000_H00_V08_tif__2_ = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\day\\tifs\\D049_Y2000_H00_V08.tif"
two = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\day\\day.gdb\\two"
day049_gdb = "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\day\\day049.gdb"

# Process: Create File GDB
arcpy.CreateFileGDB_management(day, "day049", "CURRENT")

# Process: Create Mosaic Dataset
arcpy.CreateMosaicDataset_management(day049_gdb, "day049", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "", "", "NONE", "")

# Process: Add Rasters To Mosaic Dataset
arcpy.AddRastersToMosaicDataset_management(two, "Raster Dataset", "S:\\particulates\\data_processing\\data\\MODIS_FIRE\\manual\\generated\\day\\tifs\\D049_Y2000_H00_V08.tif", "UPDATE_CELL_SIZES", "UPDATE_BOUNDARY", "NO_OVERVIEWS", "", "0", "1500", "", "", "SUBFOLDERS", "ALLOW_DUPLICATES", "NO_PYRAMIDS", "NO_STATISTICS", "NO_THUMBNAILS", "", "NO_FORCE_SPATIAL_REFERENCE")

