# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# reclassascii.py
# Created on: 2017-06-08 20:31:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
v2001_tif = "S:\\particulates\\data_processing\\data\\MODIS_LULC\\generated\\yearly\\2001.tif"
val2_txt = "S:\\particulates\\data_processing\\dofiles\\reclass\\ascii\\val2.txt"
Reclass_tif1 = "C:\\Users\\laldecol\\Documents\\ArcGIS\\Default.gdb\\Reclass_tif1"

# Process: Reclass by ASCII File
arcpy.gp.ReclassByASCIIFile_sa(v2001_tif, val2_txt, Reclass_tif1, "DATA")

