# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# reclassify.py
# Created on: 2017-06-07 18:44:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Local variables:
v2001_tif = "..\\..\\..\\data\\MODIS_LULC\\generated\\yearly\\2001.tif"
v2001_reclass_tif = "..\\..\\..\\data\\MODIS_LULC\\generated\\yearly\\manual\\2001_reclass.tif"

# Process: Reclassify
arcpy.gp.Reclassify_sa(v2001_tif, "Value", "0 0;1 6 1;7 2;8 1;8 11 2;12 4;13 5;14 4;15 6;16 3;16 255 6", v2001_reclass_tif, "DATA")

